apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: single-nodejs-app
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: single-nodejs-app
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: single-nodejs-app
  namespace: jduimovich
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: single-nodejs-app
status:
  configuration:
    generatedName: ""
