apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: single-nodejs-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: single-nodejs-app
    app.kubernetes.io/part-of: single-nodejs-app
  name: single-nodejs-app
  namespace: jduimovich
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: single-nodejs-app
    weight: 100
status: {}
